name = "galaxy-botvpn"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

keep_vars = true

[vars]
TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
GEMINI_API_KEY = "YOUR_GEMINI_API_KEY"
SERVERS_SOURCE_URL = "https://raw.githubusercontent.com/proxzero/galaxy-subdomain/main/servers.txt"
WEBSITE_URL = "https://vpn.yourdomain.com"
